### PR TITLE
Update module path for DanielOaks/girc-go to reflect new path goshuirc

### PR DESCRIPTION
**Pull request by eyedeekay**
DanielOaks/girc-go module is now goshuirc/girc-go module. This tiny change updates the module path.

### CODE REVIEW

**Comment by prologic** [comment]
Can you look into the build failures in CI by any chance?

**Comment by prologic** [comment]
Looks like those build failures are data races produced by the test suite.

Should be fixed, but can be fixed separately.

**Review by prologic — APPROVED** [review]

**Comment by eyedeekay** [comment]
Sorry for the delayed reply, I sent it in at the end of my day and I'm pretty sure we're just about on opposite sides of the world :). I can take a look at the test, IIRC we had this same thing happen last time and re-running the tests one at a time or something made it work? It was something weird like that. I'll have a look at them though.

**Comment by prologic** [comment]
It's okay. We'll fix the tests later.

There are probably legit race bugs in the code still even though I fixed quite a few a while back now :/

**Pull request merged**
