### PR TITLE
I added I2P and Tor support

### PR DESCRIPTION
**Pull request by eyedeekay**
This PR adds support for the anonymous Tor and I2P networks.

This support is largely automatic, the user adds the required configuration information to ircd.yml, keys are generated or loaded from disk as needed. The application connects to the anonymous network, then writes it's cryptographic address to the ircd.yml. This currently has the side-effect of erasing comments from the ircd.yml. Alternatively, I could write the cryptographic address to another file. This allows a user with I2P or Tor installed to use the cryptographic address in lieu of an IP address or domain name, and allow anonymous connections.

### CODE REVIEW

**Comment by prologic** [comment]
WOW! 😲 This is really cool! I have no experience with Tor, so I can't test this myself but the code LGTM.

Can we store the Tor keys in a separate file?

Can you also ensure the builds pass before I approve this? :)

**Comment by eyedeekay** [comment]
I saw some of the builds failing as I went to sleep last night, I'll see what's up with the failed ones and get it fixed as soon as I can.

The Tor keys are actually stored in a separate file, the example I added to the config places them in $PWD/tirc.torkeys. What gets written to the ircd.yml file is the .onion adddress which is the reachable part, the address which you share with people and they point an IRC client to. I can't remember the exact procedure but it's derived from the hash of the public key associated with the private key that makes you the owner of the .onion service. The content of $PWD/tirc.torkeys is the private key. The same basic thing applies for I2P, but with our API's and key formats instead of Tor's.

I don't like deleting people's comments from their config files for the sake of writing the reachable address to the configuration file, but I have to put them somewhere and it's the obvious place. The most obvious alternative is to create a file named `{addr}`.`{.onion/.b32.i2p}`.txt containing just the address.

However, if you're not opposed to the idea of outputting another configuration format for another application, I was thinking it might be more useful to output a bit of .toml that corresponds to the `[default]` section of a [Dispatch](https://github.com/khlieng/dispatch) config. So instead of just the address, something like:

        [defaults]
        name = addr
        host = .onion/.b32.i2p
        port = 6667
        server_password = ifrequired
        ssl = false

I think this is a little more readable and for people who may be self-hosting their IRC server for a small group of individuals, easier to share in that it's slightly more self-explanatory, and of course it can be copy-pasted into a Dispatch config.toml file.

Of the two approaches to writing the address to a separate file, which do you prefer? Or is there a third which you would like even better? I am happy to do it whichever way.

**Comment by prologic** [comment]
Can't we simply derive the onion address? We have the private keys so we can also drive the public keys I assume?￼￼

**Comment by eyedeekay** [comment]
Yeah we totally can, that's not the part I'm not sure about, it's the UI issue so to speak. What's tricky where to store that value so that the admin can then share it with potential IRC users. If I put it in ircd.yml, then when I call `StoreConfig()` all the comments get wiped out. So what makes sense to me, I think, is to output those values to a different file in $PWD when the .onion service is generated. What I'm wondering is how descriptive the contents of that file should be, and what format it should be in. Experienced I2P and Tor IRC users will be able to set it up using just the .onion or .b32.i2p URL, but more details will give less experienced users more guidance.

**Comment by eyedeekay** [comment]
I generated an example of what happens to your config if you instruct it to listen as both a Tor and an I2P service. This will cause the ircd.yml to be rewritten thus:

**Before:**

        mutex: {}
        network:
          name: Local
        server:
          password: ""
          # This is a hidden-only IRC service available on the I2P network
          i2plisten:
            invisibleirc:
              i2pkeys: iirc.i2pkeys
              samaddr: 127.0.0.1:7656
          # This is a hidden-only IRC service available on the Tor network
          torlisten:
            hiddenirc:
              torkeys: tirc.torkeys
              controlport: 0
          log: ""
          motd: ircd.motd
          name: myinvisibleirc.i2p
          description: Hidden IRC Services
        operator:
          admin:
            password: password
        account:
          admin:
            password: password

**After:**

        mutex: {}
        network:
          name: Local
        server:
          password: ""
          i2plisten:
            invisibleirc:
              i2pkeys: iirc.i2pkeys
              samaddr: 127.0.0.1:7656
              base32: sxe2khtg4hbl5wqpawxvfu7hcabyz732ggoqikdbi2ppfjfly5cq.b32.i2p
          torlisten:
            hiddenirc:
              torkeys: tirc.torkeys
              controlport: 0
              onion: gguxn3xbklddkpveron6itxyms5qyzj5c67wnxjmn77gar7h6btyd3qd.onion
          log: ""
          motd: ircd.motd
          name: myinvisibleirc.i2p
          description: Hidden IRC Services
        operator:
          admin:
            password: password
        account:
          admin:
            password: password

**Comment by eyedeekay** [comment]
I changed how it works, now it outputs the reachable addresses to plain-text files in $PWD, thereby not requiring the ircd.yml to be rewritten.

**Comment by prologic** [comment]
> I changed how it works, now it outputs the reachable addresses to plain-text files in $PWD, thereby not requiring the ircd.yml to be rewritten.

Cool this is better _I think_, and was my point.

I _think_ outputting this to STDOUT is fine on startup.

In addition, what if we also have a simple builtin web server and templated page that gives a little info about the running IRCD? Including how to connect to it/etc? This could work nicely for less experienced Tor/I2P users like myself :D

**Comment by eyedeekay** [comment]
> In addition, what if we also have a simple builtin web server and templated page that gives a little info about the running IRCD? Including how to connect to it/etc? This could work nicely for less experienced Tor/I2P users like myself :D

I like this idea a lot. I'll work something up and add it to this PR a little later today.

**Comment by eyedeekay** [comment]
I figured it might be useful if the templates could be in multiple languages, so I gave it a template directory and a simple default template. If you set a template directory, it will load them all and then which template is used to display the information is determined by the path. So if you have a template directory, for example `lang/`, template in `lang/en.template` it will override the default template, but if you want to have a template `lang/es.template`, it could provide you with a Spanish version of the page instead.

**Comment by prologic** [comment]
Nice! I'll test this out over the weekend if I can. I know nothing about Tor though :) Not even sure it'll work for me!

**Comment by prologic** [comment]
Can you screenshot the web app that displays hte connection info?

**Comment by eyedeekay** [comment]
It should just work automatically as long as there is a Tor daemon present with a SocksPort available at port 9050, which is normally the default. Just uncomment the default settings in the example ircd.yml. It uses cretz/bine, which is this fantastic little library that takes care of the complicated parts of the setup. I2P would require one extra step, we have a Socket API called "SAM" which you would need to enable at [http://localhost:7657/configclients](http://localhost:7657/configclients) which allows the same sort of automatic configuration. In both cases, keys should be generated and stored in $PWD automatically with obvious-looking filenames. Here's a screenshot from a system running exactly the defaults:
Screenshot_2020-11-13 Screenshot
To test a client with either Tor or I2P, Dispatch is pretty easy.

Tor
        [proxy]
        # Dispatch will make all outgoing connections through the specified proxy when enabled
        enabled = true
        protocol = "socks"
        host = "127.0.0.1"
        port = 9050

For I2P:
        [proxy]
        # Dispatch will make all outgoing connections through the specified proxy when enabled
        enabled = true
        protocol = "i2p"
        host = "127.0.0.1"
        port = 7656

**Pull request merged**
